### ISSUE TITLE
WM_WINDOW_ROLE is not supported by Qt5+Linux

### ISSUE THREAD

**Issue by shunlir** [double-commander/doublecmd#10]
I have recently switched to doublecmd-qt5, it's awesome, but I find WM_WINDOW_ROLE is missed.

There was a PR(https://github.com/double-commander/doublecmd/commit/a4a1c77cd7bef32aafc7007d892f86390b8f702e) that added WM_WINDOW_ROLE support for GTK2/Qt4 + Linux(seems Unix build and non Darwin), but the same functionality is not available in Qt5.
The WM_WINDOW_ROLE is quite useful for tiding window manager, please see this thread for the reason behind it: https://doublecmd.sourceforge.io/forum/viewtopic.php?p=18544&sid=419a36e6490628351593d3e90af26866#p18504

Thanks,

**Comment by alexx2000** [comment]
Added.

**Comment by Neustradamus** [comment]
@shunlir: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
