### ISSUE TITLE
Bug: need to press Enter several times to change directory

### ISSUE THREAD

**Issue by eldaragalarov** [double-commander/doublecmd#12]
Hi. Sometimes I have annoying bug. When I'm pressing Enter to enter inside directory then I get following: 

1. Path above file list is changing properly
2. File list itself not (directory remains the same). Need to press Enter several times or press Left button to get back and press Enter again.
3. "loading file list.." is printed below file list.

Ubuntu 21.04
Doublecmd 0.9.10 beta

**Comment by TheNicker** [comment]
0.9.10 is quite old, does it happen with recent versions ?

**Comment by EldarAgalarov** [comment]
Tested on 1.0.0 alpha (revision 9845) - the same problem happens.

Similar problem discussed on [DC forum](https://doublecmd.h1n.ru/viewtopic.php?t=1544) but suggested solution not resolved this issue.

**Comment by Neustradamus** [comment]
@EldarAgalarov: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
