### ISSUE TITLE
Overwrite all Equal

### ISSUE THREAD

**Issue by msjasinski** [double-commander/doublecmd#17]
In Copy F5/ Move F6 in case of conflict there is a menu with options such as
Rename / Overwrite all Smaller / etc

I need another option:
"Overwrite all Equal"

This is what I usually do (manually) when merging contents from different devices.

Thanks for this great program. All the best!

**Comment by Neustradamus** [comment]
@msjasinski: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/issues/134
