### ISSUE TITLE
[feature request] Search options

### ISSUE THREAD

**Issue by Frydac** [double-commander/doublecmd#18]
Hi,

Just a suggestion that would make it a bit easier to find that one option, imho.

There are many configuration options, they are categorized adequately, but still there are a lot of categories, searching for a specific option, that I don't know for sure is there, can be quite time consuming. (Just going over all the categories and thinking if it should fit there is already a task of a few minutes, I tend to resort to google now to find where an option can be found in the GUI).

Some sort of search box in the Configuration->Options window, possibly search while you type, that reduces/highlights the categories/UI elements that contain the search string could be helpful.

**Comment by alexx2000** [comment]
Added in the 1.1.0 version.

**Comment by Neustradamus** [comment]
@Frydac: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
