### ISSUE TITLE
please add hebrow language

### ISSUE THREAD

**Issue by AshiVered** [double-commander/doublecmd#23]
i can to help in tranlation.
thank you on your work!

**Comment by rabin-io** [comment]
@alexx2000 I don't know if you are using it, but there are a few services, which allow for collaborative translating. Transifex was one of the good ones, but now they cost a lot, there are alternatives, like Weblate and Zanata. 

This should open the option for others to contribute translations.

**Comment by WhiteChairFromIkea** [comment]
Webplate is very userfriendly, I am using it for another project

**Comment by Neustradamus** [comment]
@AshiVered, @WhiteChairFromIkea: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/issues/192
