### ISSUE TITLE
Concurrent usage of DC and TC when only one instance is allowed

### ISSUE THREAD

**Issue by gergelyGcsikvari** [double-commander/doublecmd#25]
Hi, an interesting phenomenom I observed recently. When I set "allow only one instance" in Total Commander (TC) then I can't start it if DC is already running. (I did not try but I guess the same happens on the reversed setup).
 I checked the code of DC but did not brought me really closer to my suspicion that the two apps are using the same (OS) object to register the instances...well I'm not really familiar with Delphi, it was roughly 20 years ago last time I dealt with Pascal...

**Comment by alexx2000** [comment]
Hi, DC use same window class as TC for compatibility with TC plugins. So, yes it cannot be used together with TC in this case.

**Comment by Neustradamus** [comment]
@gergelyGcsikvari: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
