### ISSUE TITLE
Allow pass directories to external differ

### ISSUE THREAD

**Issue by SAASTN** [double-commander/doublecmd#26]
Hi,
Many diff tools (e.g. WinMerge) can also compare contents of directories. But running the "Compare By Contents" in DC, when directories are selected, will show an error message saying : "Invalid selection.".
It also can be a different command than `cm_CompareContents` that sends both open directories themselves to the external differ.

BTW, I cannot find the syntax that DC uses for sending additional parameters. It seems that it is a fixed syntax like:
```
[external app path] [additional parameters] [left file path] [right file path]
```
It's a good idea to allow paths of files to be sent in a more flexible way. For example they can be explicitly mentioned in "Additional Parameters" as defined variables, like `$left` and `$right` or something. But if these variables were not present in "Additional Parameters", the default syntax can be used. This can be useful in cases when more additional parameters should be passed after paths of files. For example, WM can take a third path to store the merged results. In this case the Additional Parameters can be something like this:
```
/u /e $left $right /o "c:\somefile.txt"
```

Thanks for the grate app
Regards

**Comment by SAASTN** [comment]
I submitted this in the main repo. I'm confused, which issues should be submitted here?

**Comment by Neustradamus** [comment]
@SAASTN: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7

**Comment by SAASTN** [comment]
> @SAASTN: The official and good organization/repository:
> 
> * https://github.com/doublecmd/
> * https://github.com/doublecmd/doublecmd
> 
> Please open at the good place.
> 
> Linked to:
> 
> * [Warning: Official place is not here #7](https://github.com/double-commander/doublecmd/issues/7)

Yeah, already there: [#394](https://github.com/doublecmd/doublecmd/issues/394)
Thanks for the clarification though.
