### ISSUE TITLE
[bug] Sort oprtions not work with directories 

### ISSUE THREAD

**Issue by savegame** [double-commander/doublecmd#27]
|Version:|0.9.10 beta|
|:-|-:|
|Revision:|9640|
|Build date:|2021/02/14|
|Lazarus:|2.0.10.0|
|FPC:|3.2.0|
|Platform:|x86_64-Linux-qt5|
|OS version:|Pop!_OS 21.10|
|Widgetset library:|Qt 5.15.2, libQt5Pas 5.6.1|  

few screenshots with different sort options selected   
![изображение](https://user-images.githubusercontent.com/16311332/163667942-989bc11c-95cf-4fdc-b1f2-6a5491b73491.png)  
![изображение](https://user-images.githubusercontent.com/16311332/163667948-03594f10-16a6-482e-ae11-a640c3f8dc51.png)  
![изображение](https://user-images.githubusercontent.com/16311332/163667963-4a6d42d6-ce69-434c-a60a-a6dead0a4f9d.png)

**Comment by savegame** [comment]
oh! i think i found some option about this sorting :-) 
sorry, looks like it not an issue :smile: 
`Settings -> Files List -> Directories Sorting`

**Comment by Neustradamus** [comment]
@savegame: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
