### ISSUE TITLE
no input from keyboard when opening new tab while file quick search is open

### ISSUE THREAD

**Issue by kgabor545** [double-commander/doublecmd#28]
1. quicksearch for a directory by typeing its name
2. ctrl+up to open in new tab
3. can't use keyboard on the new tab (until clicking or activating tab with alt+num)
it occurs also when the tab is locked, so without ctrl+up a new tab opens automatically
 
v1.0.6 beta

**Comment by kgabor545** [comment]
opened in official repo

**Comment by Neustradamus** [comment]
The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
