### ISSUE TITLE
Doublecmd logs out of session randomly

### ISSUE THREAD

**Issue by srikk73** [double-commander/doublecmd#29]
### Description

Doublecmd logs out of session randomly or screen will go blank. 

I fetched latest code from github and built it.

### Steps to reproduce

1. Login to Linux system
2. Open Doublecmd
3. Keep using for some time

### Expected Behavior
Doublecmd will keep running without any problem.

### Actual Behavior
After sometime of using it, one of these two events will occur:

* The screen will go blank for some seconds and come back to the session. All the applications are running. This event may happen several times.
* The screen will go blank and **the session will log out**. We will login again and it is a new session. All the applications in the old session will be stopped.

### System 
Linux **5.15.60-1-MANJARO** #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux
Release:        **21.3.7**

**Comment by srikk73** [comment]
Sorry, I am using the official branch, not this branch. Please ignore.

**Comment by Neustradamus** [comment]
@srikk73: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7

**Comment by alexx2000** [comment]
https://github.com/doublecmd/doublecmd/issues/573
