### ISSUE TITLE
Migrate to qt5

### ISSUE THREAD

**Issue by rsanjuan87** [double-commander/doublecmd#3]
Hi nice work
I recently downloaded the app and I see that it is made with qt4
a migration to qt5 could be proposed?
the biggest reason for this is that I have the dark theme in MacOS and qt4 does not take it

**Comment by TheNicker** [comment]
You've probably downloaded an old build and it wasn't from this repository.
Double commander should already be compatible with QT5, it's a matter of build configuration.

This repository currently maintains only Windows builds so either find a prebuilt binary for MacOS with QT5 or build it yourself.
If you do decide to build it yourself, the build can be uploaded to this repository so dark theme and other goodies would work for the next person.

**Comment by Neustradamus** [comment]
@rsanjuan87: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7

**Comment by alexx2000** [comment]
macOS version use native Cocoa library now. So this issue is obsolete. You can download it from [here](https://sourceforge.net/p/doublecmd/wiki/Download-Beta).
