### ISSUE TITLE
Confirmation Window still shows even though it's unchecked

### ISSUE THREAD

**Issue by trunterzx** [double-commander/doublecmd#31]
I unchecked the option to show confirmation window for copy and move operation under file operations, but it still shows the confirmation window. I'm using the windows version (1.1.0~10438). Any ideas why?

**Comment by trunterzx** [comment]
> doublecmd/doublecmd#641

Thanks! Solved the problem

**Comment by Neustradamus** [comment]
@trunterzx: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Linked to:
- https://github.com/double-commander/doublecmd/issues/7
